### ISSUE TITLE
[11.0] mail_debrand not working

### ISSUE THREAD

**Issue by bishamontn** [OCA/social#390]
Hello,

I have installed an Odoo v11 and I have created an Odoo database without just with sale app and no custom addons. Sending the email with just the sample data I am getting the default Odoo email with all the Odoo branding, so I think this addon is not working because I have nothing incompatible in my installation.

<img width="1110" alt="Captura de pantalla 2019-06-03 a las 16 22 50" src="https://user-images.githubusercontent.com/5429131/58809355-0f92dc80-861c-11e9-9c13-79737bcd3fec.png">

Any help is welcome.

**Comment by Ark74** [comment]
Are these two related?
https://github.com/OCA/social/issues/390
https://github.com/OCA/social/issues/441

**Comment by pedrobaeza** [comment]
Yes, and they should be fixed by #507, so closing.

**Comment by Ark74** [comment]
Hmm, applied the last fix and I'm still getting the " Impulsado por Odoo. " (on Spanish) when sending an RFQ.
Maybe it's "Powered by Odoo" instead of "Using Odoo" in my case (as shown in the picture above).

**Comment by pedrobaeza** [comment]
You have to make the translation in this module to match your sentence
